resolver: lts-17.3

packages:
- ./lib/gzc-core
- ./lib/gzc-parser
- .

extra-deps:
- git: https://github.com/mesabloo/diagnose.git
  commit: c6223edb04c952eda4794ce9fc99817f1bfc66c6
- git: https://github.com/zilch-lang/nsc.git
  commit: 8a9d1d5aa19fe6493c556ae3606c758829683762
  subdirs:
  - lib/nsc-core

allow-newer: true

nix:
  shell-file: stack-shell.nix
  add-gc-roots: true
